---
services:
  patcher:
    build: .
    volumes:
      - .:/apk
    environment:
      - APK_FILE=/apk/Tapped Out.apk
      - SOURCE_OUTPUT=/apk/decompiled
      - GAMESERVER_URL=http://1.2.3.4:9000
      - DIRECTOR_URL=http://1.2.3.4:9000
      - DLC_URL=http://1.2.3.4:9000/static
      - APK_SHA256SUM=
